services:

  metastore:
    image: redis:5.0
    volumes:
      - type: bind
        source: ${NEXOEDGE_DATA_DIR}/metadata
        target: /data

  proxy:
    image: nexoedge-proxy:${TAG}
    ports:
      - "57002:57002"
    environment:
      NCLOUD_PROXY_Metastore_Ip: "metastore"
      NCLOUD_PROXY_Reporter_db_Ip: "statsdb"
      NCLOUD_PROXY_Reporter_db_Port: "8080"
      NCLOUD_PROXY_Dedup_Enabled: "0"
      NCLOUD_GENERAL_Log_GLog_to_console: "1"
    depends_on:
      - metastore
      - statsdb

  storage-node-01:
    image: nexoedge-agent:${TAG}
    #ports:
    #  - "57003:57003"
    #  - "57004:57004"
    environment:
      NCLOUD_AGENT_Agent_Num_containers: "2"
      NCLOUD_AGENT_Container01_Id: "1"
      NCLOUD_AGENT_Container02_Id: "2"
      NCLOUD_AGENT_Container01_Capacity: "107374182400"
      NCLOUD_AGENT_Container02_Capacity: "107374182400"
      NCLOUD_AGENT_Container01_Url: "/data01"
      NCLOUD_AGENT_Container02_Url: "/data02"
      NCLOUD_GENERAL_Proxy01_Ip: "proxy"
    volumes:
      - type: bind
        source: ${NEXOEDGE_DATA_DIR}/container01
        target: /data01
      - type: bind
        source: ${NEXOEDGE_DATA_DIR}/container02
        target: /data02
    depends_on:
      - proxy

  storage-node-02:
    image: nexoedge-agent:${TAG}
    #ports:
    #  - "57003:57003"
    #  - "57004:57004"
    environment:
      NCLOUD_AGENT_Agent_Num_containers: "2"
      NCLOUD_AGENT_Container01_Id: "3"
      NCLOUD_AGENT_Container02_Id: "4"
      NCLOUD_AGENT_Container01_Capacity: "107374182400"
      NCLOUD_AGENT_Container02_Capacity: "107374182400"
      NCLOUD_AGENT_Container01_Url: "/data01"
      NCLOUD_AGENT_Container02_Url: "/data02"
      NCLOUD_GENERAL_Proxy01_Ip: "proxy"
    volumes:
      - type: bind
        source: ${NEXOEDGE_DATA_DIR}/container03
        target: /data01
      - type: bind
        source: ${NEXOEDGE_DATA_DIR}/container04
        target: /data02
    depends_on:
      - proxy

  cifs:
    image: nexoedge-cifs:${TAG}
    ports:
      - "445:445"
    volumes:
      - type: bind
        source: ${NEXOEDGE_DATA_DIR}/cifs-metadata
        target: /usr/local/samba/var
      - type: bind
        source: ${NEXOEDGE_DATA_DIR}/cifs-share-metadata
        target: /smb/nexoedge
    depends_on:
      - proxy

  statsdb:
    image: helenchw/restful-logdb
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ${NEXOEDGE_DATA_DIR}/logdb-data
        target: /my_db
      - type: bind
        source: ./logdb-config.ini
        target: /config.ini

  reporter:
    image: nexoedge-reporter:${TAG}
    environment:
      NCLOUD_GENERAL_Proxy01_Ip: "proxy"
      NCLOUD_PROXY_Reporter_db_Ip: "statsdb"
      NCLOUD_PROXY_Reporter_db_Port: "8080"
    depends_on:
      - proxy

  #portal-frontend:
  #  image: nexoedge-admin-portal:${TAG}
  #  ports:
  #    - "80:80"
  #  environment:
  #    WEBDIS_REDIRECT_ADDR: "statsdb"
  #  depends_on:
  #    - statsdb

  #http-proxy:
  #  image: nginx
  #  ports:
  #    - "80:80"
  #  environment:

